// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// #AgentTeamsInput is the `agentteams` verb's plugin_input: the method name plus
// its method-exclusive modifiers.
type AgentTeamsInput struct {
	// method — the agentteams verb method name (the verb's PRIMARY input field, so
	// `agentteams: status` desugars to {method: "status"}).
	Method string `yaml:"method,omitempty" json:"method"`

	// name — the worker/manager name. worker-running's target (default "bed-worker",
	// matching the beds' created Worker CR); manager-running's optional specific
	// manager (default: any manager reaching Running).
	Name string `yaml:"name,omitempty" json:"name,omitempty"`
}
